services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"    # MySQL 포트 매핑
    volumes:
      - ./db_data:/var/lib/mysql  # 볼륨 마운트 설정
    networks:
      - pill-net

  backend:
    image: pill/backend
    build:
      context: ./backend
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      - db
    ports:
      - "8080:8080"    # 스프링부트 포트 (필요에 따라 수정)
    networks:
      - pill-net
    restart: always

networks:
  pill-net:
    driver: bridge

volumes:
  db_data:
